### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by LagHD** [jackthehack21/MCPEToDiscord#1]
Would be cool if it was possible from Discord to MCPE too

**Comment by jackthehack21** [comment]
@LagHD This plugin IS from MCPE to discord

**Comment by LagHD** [comment]
I meant from discord to MCPE srry xD

**Comment by jackthehack21** [comment]
@LagHD That is a hard request because I use webhook via discord, this won’t be considered unless a new method is found
But do you want to see any new plugins I’m currently deciding what to make next

**Comment by LagHD** [comment]
Sure

**Comment by jackthehack21** [comment]
@LagHD 🤔 interesting so a plugin that rewards the player if you break a certain block ?

**Comment by LagHD** [comment]
Yes, that would be awesome!

**Comment by jackthehack21** [comment]
@LagHD This request was added to my list and hopefully will be out soon on my repos, this issue will now be closed.

**Comment by jackthehack21** [comment]
@LagHD Your plugin has been in progress over at https://github.com/jackthehack21/BlockReward
