### ISSUE TITLE
PureChat Compatability

### ISSUE THREAD

**Issue by Haxley** [jackthehack21/MCPEToDiscord#10]
**Is your feature request related to a problem? Please describe.**
If you use PureChat with this plugin it will display color symbols, placeholders, and whatnot. 

**Describe the solution you'd like**
Add compatibility with PureChat

**Describe alternatives you've considered**
Removing PureChat, which isn't an option. 

**Additional context**

**Comment by jackthehack21** [comment]
Hi there Haxley,
With regards to PureChat would you like to see configure options to enable/disable the PureChat ?
And by this request do you mean that you would like to see the purechat nickname in discord, could you please just clarify what you want PureChat compatibilty would add to MCPEToDiscord !

**Comment by Haxley** [comment]
I guess just an option to enable/disable purechat. As, purechat supports other plugins (i.e. factions), it would probably be a lot of work for full purechat support. I just changed the line to use display name like the rest of them as a quick fix, but config setting would be better. If you think it wouldn't be too hard to support factions suffixes, prefixes, section symbols, etc... by all means, go for full purechat support. Otherwise, a simple config option that toggles onPlayerChat to use display name would suffice.

**Comment by jackthehack21** [comment]
I will be adding PureChat Support in next major update, this will probably include these config options:
PureChat: enables

And in the format you will be  able to add {group}, {nickname}, {name}

Any further questions please don’t hesitate.

**Comment by jackthehack21** [comment]
Faction Support will be added (Name and Rank)
PureChat Support will be added (Group and Nickname)

**Comment by jackthehack21** [comment]
This has all been added except PureChat but that may come soon, i hope this helps.
