### ISSUE TITLE
Suggestions for Chinese-user related stuff

### ISSUE THREAD

**Issue by GdBai** [jackthehack21/MCPEToDiscord#15]
Hi Jack,

Good job on this plugin! I have two suggestions:

1. The Chinese commands translation seems to be google-translated so there are some mistakes. I can help improve the translation if you like :)

2. Unfortunately, the Chinese government has contaminated the usual DNS domain for Discord (in July 2018). I found this news after several unsuccessful attempt to deploy MCPEToDiscord from a Shanghai based server. The solution is adding these into /etc/hosts (or any location of your hosts file):

> 104.16.248.144 dl.discordapp.net
> 104.16.60.37 gateway.discord.gg
> 104.16.11.231 status.discordapp.com
> 104.16.9.231 cdn.discordapp.com
> 104.16.59.5 discordapp.com
> 104.16.250.144 media.discordapp.net
> 104.16.249.144 images-ext-2.discordapp.net
> 104.16.250.144 images-ext-1.discordapp.net
> 151.101.78.214 static-cdn.jtvnw.net

If you could consider add these to wiki or poggit, thx!

**Comment by jackthehack21** [comment]
Hi there thanks for this feedback, I was in aware of anything going on in China as I live in the UK.
Regarding the translations and hosts, feel free to create a pull request to add/fix the mentioned.
