### ISSUE TITLE
Discord To Minecraft (2-way)

### ISSUE THREAD

**Issue by osybear1** [jackthehack21/MCPEToDiscord#17]
I would like some features that DiscordSRV plugin adds. Here is the link to the plugin.
https://www.spigotmc.org/resources/discordsrv.18494/
If atleast anything. Find a way to add support for message to and from the discord.

**Comment by jackthehack21** [comment]
Hi there,

Right, so for that to work at all it would require more user setting up, setting up a bot and adding it to your server.

And for the plugin to be running that bot
Meaning it may cause more lag if it’s done.

I’m unsure yet if this plugin is to continue progress, I do have other projects right now but if this does get a lot of attention I will be more then happy to implement it.

- Jack


Users who are viewing this please comment your views.

**Comment by jackthehack21** [comment]
This project will probably stay on PMMP but not two way as another plugin has already achieved that !
Check it out at <https://github.com/JackNoordhuis/DiscordRelay-PocketMine>
