### ISSUE TITLE
Players are able to abuse mentions.

### ISSUE THREAD

**Issue by 95CivicSi** [jackthehack21/MCPEToDiscord#18]
**Describe the bug**
Players are able to use mentions/tags such as @everyone and @here from the Minecraft server with no plugin side options to nullify this behavior.

**To Reproduce**
1. Setup plugin and Discord
2. Log into running server.
3. Try using @everyone

**Expected behavior**
MCPEToDiscord should recognize tags like this and break them so that it's not possible to spam Discord members with notification from inside the MCPE server.

**Screenshots**

**Pocketmine Version**
3.8.1

**MCPEToDiscord Version**
Build - 187A

**Comment by jackthehack21** [comment]
Thanks for the report, it’s been known for a very long time but I haven’t had as the one time I get round to  fixing it, my plan was to make a banned words list and have the default mentions in that list.
Will be fixed in 1.4.1

**Comment by jackthehack21** [comment]
Feel free to use 1.4.1 branch for a quick fix, it should remain stable but again its a dev build expect the un-expected.
Will be with 1.4.1 once i add a few other things from my todo list.
