### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JamXDrew** [jackthehack21/MCPEToDiscord#3]
Doesnt semd message on discord or ingame

**Comment by jackthehack21** [comment]
Please provide all details
Pocketmine version, MCPE version
Plugin version and show the config.yml

**Comment by jackthehack21** [comment]
This issue will be closed,
All 60 users have been able to use this utility and no one has reported this kind of issue I have released a new update to poggit with new languages support
However if you feel this update does not fix it or your still having trouble please contact me on discord (Jackthehaxk21#8860)
