### ISSUE TITLE
help

### ISSUE THREAD

**Issue by cujowilliams123** [jackthehack21/MCPEToDiscord#8]
Server thread/CRITICAL Error: "Call to undefined method pocketmine\Server::getAsyncPool()" (EXCEPTION) in "MCPEToDiscord/src/Jack/DiscordMCPE/Main" at line 294
23.06 23:45:08 [Server] Server thread/DEBUG #0 MCPEToDiscord/src/Jack/DiscordMCPE/Main(94): Jack\DiscordMCPE\Main->sendMessage(string Disabled, string Plugin Disabled !)
23.06 23:45:08 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/PluginBase(92): Jack\DiscordMCPE\Main->onDisable()
23.06 23:45:08 [Server] Server thread/DEBUG #2 PocketMine-DevTools.phar/src/FolderPluginLoader/FolderPluginLoader(146): pocketmine\plugin\PluginBase->setEnabled(boolean )
23.06 23:45:08 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(653): FolderPluginLoader\FolderPluginLoader->disablePlugin(Jack\DiscordMCPE\Main object)
23.06 23:45:08 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginManager(579): pocketmine\plugin\PluginManager->disablePlugin(Jack\DiscordMCPE\Main object)
23.06 23:45:08 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1919): pocketmine\plugin\PluginManager->enablePlugin(Jack\DiscordMCPE\Main object)
23.06 23:45:08 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1905): pocketmine\Server->enablePlugin(Jack\DiscordMCPE\Main object)
23.06 23:45:08 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1988): pocketmine\Server->enablePlugins(integer 1)
23.06 23:45:08 [Server] Server thread/DEBUG #8 src/pocketmine/command/defaults/ReloadCommand(49): pocketmine\Server->reload()
23.06 23:45:08 [Server] Server thread/DEBUG #9 src/pocketmine/command/SimpleCommandMap(258): pocketmine\command\defaults\ReloadCommand->execute(pocketmine\command\ConsoleCommandSender object, string reload, array Array())
23.06 23:45:08 [Server] Server thread/DEBUG #10 src/pocketmine/Server(1946): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\command\ConsoleCommandSender object, string reload)
23.06 23:45:08 [Server] Server thread/DEBUG #11 src/pocketmine/Server(1931): pocketmine\Server->dispatchCommand(pocketmine\command\ConsoleCommandSender object, string reload)
23.06 23:45:08 [Server] Server thread/DEBUG #12 src/pocketmine/Server(2492): pocketmine\Server->checkConsole()
23.06 23:45:08 [Server] Server thread/DEBUG #13 src/pocketmine/Server(2243): pocketmine\Server->tick()
23.06 23:45:08 [Server] Server thread/DEBUG #14 src/pocketmine/Server(2119): pocketmine\Server->tickProcessor()
23.06 23:45:08 [Server] Server thread/DEBUG #15 src/pocketmine/Server(1701): pocketmine\Server->start()
23.06 23:45:08 [Server] Server thread/DEBUG #16 src/pocketmine/PocketMine(305): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)Add any other context about the problem here.

**Comment by jackthehack21** [comment]
You are using a old version of PocketMine-MP that the latest release does not support, get the latest pocketmine phar, or go to releases on this GitHub for a earlier release of MCPEToDiscord

You are getting this error as you have a old version of PocketMine.

**Comment by cujowilliams123** [comment]
ok thanks

**Comment by TheJoMinecraft** [comment]
Ich fersehe es nicht kannst. Du mir helfen

**Comment by Dragonblitz10** [comment]
Möchten Sie Hilfe bei der Verwendung des Plugins in deutscher Sprache oder haben Sie ein Problem?

**Comment by jackthehack21** [comment]
Vergewissern Sie sich, dass Sie die richtige Webhook-URL in plugin config.yml eingerichtet haben, und es gibt weitere Hilfspunkte in README und help.txt

**Comment by Dragonblitz10** [comment]
Um einen Webhook zu erstellen, schauen Sie in diesem Handbuch nach https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22

**Comment by TheJoMinecraft** [comment]
Hallo!
Ich möchte dieses plugin bei aternos.org einfügen was nicht geht

Dragonblitz10 <notifications@github.com> schrieb am So., 17. März 2019,
14:25:

**Comment by jackthehack21** [comment]
![35822E8A-DD6E-486C-B04F-A753C18942A5](https://user-images.githubusercontent.com/25908768/54492088-6f020b80-48bb-11e9-8d45-ef06d96196f7.png)
![FE3A5965-6A3A-4CA0-8832-C6E1B34767EB](https://user-images.githubusercontent.com/25908768/54492089-6f9aa200-48bb-11e9-87b1-4f9a1bbf9192.png)
![BA5D1D26-3C44-4523-97C8-1BFE06B95CA9](https://user-images.githubusercontent.com/25908768/54492090-6f9aa200-48bb-11e9-9c67-c77df9e589ba.png)
![F268E9B0-6138-44AC-88F2-BF9F2B41C31F](https://user-images.githubusercontent.com/25908768/54492091-6f9aa200-48bb-11e9-95b1-1602ada7df28.png)

**Comment by jackthehack21** [comment]
Das ist alles, was ich sagen kann, wenn Sie weitere Hilfe benötigen, sprechen Sie mit Ihrem Host-Provider.

**Comment by TheJoMinecraft** [comment]
Aber weiter geht es nicht!
Es gibt kein bot der sich connected kan oder so

Jack Honour <notifications@github.com> schrieb am So., 17. März 2019, 14:49:
